### ISSUE TITLE
Lightdm

### ISSUE THREAD

**Issue by ghost** [artix-linux/iso-profiles#11]
Lightdm is being used for Cinnamon though you do not appear to have any lightdm packages anywhere

**Comment by cromerc** [comment]
If you are referring to there not being a lightdm in our repos, that is because it is in arch's which are active. No need for us to rebuild lightdm since it doesn't have any systemd pollution.

If that is not what you meant, could you please elaborate more?

**Comment by ghost** [comment]
This clearly says https://github.com/artix-linux/iso-profiles/blob/master/cinnamon/profile.conf
displaymanager is lightdm
My understanding is this will only work if lightdm files are in the package lists?

**Comment by ghost** [comment]
Found it is possible to amend the netgroups-openrc.yaml file and have it load by the /etc/calamares/modules/netinstall.conf file. So the above does not matter.
